### ISSUE TITLE
use headless browser for imdb interactions

### ISSUE THREAD

**Issue by cecobask** [cecobask/imdb-trakt-sync#39]
IMDb changed how lists and ratings are exported.
We used to be able to get the data using the `/export` endpoint, which now returns a 404 error.
The only workaround is to refactor the IMDb interactions to be based on headless browsing with one of the tools below:
- https://github.com/go-rod/rod
- https://github.com/chromedp/chromedp

**Comment by aktur** [comment]
+1

**Comment by BardaktakiAdam** [comment]
![image](https://github.com/cecobask/imdb-trakt-sync/assets/43864069/368aa042-e425-42ce-957d-041938e2e245)

**Comment by cecobask** [comment]
Hi folks, I've started working on the issue. I should have a fix available later this week.
I maintain this project in my spare time and I've been busy lately, thanks for understanding!

**Comment by Tetrax-10** [comment]
Here is my [work around](https://github.com/Tetrax-10/import-imdb-lists-to-tmdb/blob/main/src/utils/imdbListCsvDownloader.js) to download CSV from IMDb with a headless browser.

**Comment by BardaktakiAdam** [comment]
Hi, problem is still the same for me 

![image](https://github.com/cecobask/imdb-trakt-sync/assets/43864069/5613484a-fb09-4d31-9032-95fbf3eeda15)

**Comment by cecobask** [comment]
Hi @BardaktakiAdam, you definitely need to sync your fork with the origin. After doing that you will have to check your repository secrets and make sure they match the latest configuration.
